[package]
name = "weathermap-cargo-rust-only"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15"
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1.0.141"
tokio = { version = "1", features = ["full"] }
